function cellInfo = initBusDef(n) 
% CONTROL_BUSDEF returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

naviBusInfo={...
    {'atmosBus', '', 'atmospheric data', 'Auto', '-1', {...
        {'T',      1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'p',      1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'rho',    1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'alpha',  1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'beta',   1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'Va',     1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'omegaA', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'vWind',     3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'omegaW', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
    }},...
        {'propulsionBus', '', 'state of propulsion system', 'Auto', '-1', {...
        {'OmegaProps', n, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
    }},...
        {'rigidbodyBus', '', 'state of rigid body motion', 'Auto', '-1', {...
        {'Vecef',                           3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'Xecef',                           3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'llh',                             3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'xg',                              3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'euler',                           3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'Tfi',                        [3, 3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'Tfg',                        [3, 3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'Vb',                              3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'omega',                           3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'gamma',                           1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'chi',                             1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'Vg',                              3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'quat',                            4, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
    }},...
        {'utilityBus', '', 'utility data', 'Auto', '-1', {...
        {'HaG', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'omega_dot', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'specific_nongravitational_force', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'acc', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
    }},...
    {'fmBus', '', 'flight mechanical simulation', 'Auto', '-1', {...
        {'rigidbodyBus',  1, 'rigidbodyBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'atmosBus',      1, 'atmosBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'propulsionBus', 1, 'propulsionBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        {'utilityBus',    1, 'utilityBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
    }},...
};

    Simulink.Bus.cellToObject(naviBusInfo)
end 

